import { SafariPackage } from "@/types";

export const safariPackages: SafariPackage[] = [
  {
    id: "day-trip-mikumi",
    titleFr: "Day Trip Safari — Mikumi National Park",
    titleEn: "Day Trip Safari — Mikumi National Park",
    descriptionFr: "Le Safari d'une journée à Mikumi National Park pour faire la visite dans le parc. Départ à 5h du matin, vol direct aller-retour, safari en jeep avec déjeuner inclus.",
    descriptionEn: "A one-day safari to Mikumi National Park. Departure at 5am, direct round-trip flight, jeep safari with lunch included.",
    duration: "1 Journée",
    price: "380€ par personne",
    coverImage: "/images/Day trip Safari.jpeg",
    images: [
      "/images/Day trip Safari.jpeg",
      "/images/Day trip Safari 2.jpeg",
      "/images/Day trip Safari 3.jpeg",
    ],
    itineraryFr: [
      {
        day: 1,
        title: "Zanzibar → Mikumi → Zanzibar",
        description: "5h du matin le chauffeur va vous chercher et vous amène jusqu'à l'aéroport. Vous partez avec les autres personnes avec l'avion directement dans le parc. Vous faites la visite jusqu'à 12h, déjeuner, puis vous rentrez dans le parc jusqu'à 16h30. Ensuite vous prenez l'avion et rentrez à Zanzibar. Le chauffeur va vous chercher à l'aéroport et vous amène à l'hôtel.",
      },
    ],
    itineraryEn: [
      {
        day: 1,
        title: "Zanzibar → Mikumi → Zanzibar",
        description: "At 5am, the driver picks you up and takes you to the airport. You leave with other people by plane directly to the park. You visit until 12pm, lunch, then back in the park until 4:30pm. Then you take the plane back to Zanzibar. The driver picks you up at the airport and takes you to the hotel.",
      },
    ],
    includedFr: [
      "Transfert hôtel ↔ aéroport (2 fois)",
      "Vol aller-retour Zanzibar-Mikumi",
      "Entrée au parc",
      "Jeep 4x4 pour le safari",
      "Déjeuner dans le parc",
      "Boissons",
      "Safari en général",
    ],
    includedEn: [
      "Hotel ↔ airport transfer (2 times)",
      "Round-trip flight Zanzibar-Mikumi",
      "Park entry fee",
      "4x4 jeep for safari",
      "Lunch in the park",
      "Drinks",
      "General safari",
    ],
  },
  {
    id: "tarangire-ngorongoro-2days",
    titleFr: "2 Jours 1 Nuit — Tarangire & Ngorongoro",
    titleEn: "2 Days 1 Night — Tarangire & Ngorongoro",
    descriptionFr: "Safari de 2 jours 1 nuit à Tarangire et le cratère du Ngorongoro. Options d'hébergement : Farm of Dreams Lodge, Simba Lodge, ou Acacia Farm Lodge.",
    descriptionEn: "2 days 1 night safari to Tarangire and Ngorongoro Crater. Accommodation options: Farm of Dreams Lodge, Simba Lodge, or Acacia Farm Lodge.",
    duration: "2 Jours / 1 Nuit",
    price: "Sur demande",
    coverImage: "/images/Safari à Tarangire et 1.jpeg",
    images: [
      "/images/Safari à Tarangire et 1.jpeg",
      "/images/Safari à Tarangire et 2.jpeg",
      "/images/Safari à Tarangire et 3.jpeg",
      "/images/Safari à Tarangire et 4.jpeg",
    ],
    itineraryFr: [
      {
        day: 1,
        title: "Zanzibar → Arusha → Tarangire → Karatu",
        description: "Volez de Zanzibar à Arusha puis vous serez pris en charge à l'aéroport d'Arusha pour une journée complète de safari dans le parc national de Tarangire. Déjeuner dans le parc. En soirée, vous rendez à Karatu pour le dîner et la nuit au lodge choisi (Farm of Dreams Lodge, Simba Lodge ou Acacia Farm Lodge).",
      },
      {
        day: 2,
        title: "Ngorongoro → Arusha → Zanzibar",
        description: "Petit-déjeuner le matin, puis de 06h30 à 07h00, départ pour la visite du cratère du Ngorongoro jusqu'à l'après-midi. Pique-nique dans le cratère. Retour à l'aéroport d'Arusha pour prendre votre vol de retour à Zanzibar.",
      },
    ],
    itineraryEn: [
      {
        day: 1,
        title: "Zanzibar → Arusha → Tarangire → Karatu",
        description: "Fly from Zanzibar to Arusha and be picked up at Arusha airport for a full day safari in Tarangire National Park. Lunch in the park. In the evening, head to Karatu for dinner and overnight at your chosen lodge (Farm of Dreams Lodge, Simba Lodge or Acacia Farm Lodge).",
      },
      {
        day: 2,
        title: "Ngorongoro → Arusha → Zanzibar",
        description: "Breakfast in the morning, then from 6:30am to 7:00am, depart for the Ngorongoro Crater visit until afternoon. Picnic in the crater. Return to Arusha airport for your flight back to Zanzibar.",
      },
    ],
    includedFr: [
      "Prise en charge et retour à l'aéroport d'Arusha",
      "Vol intérieur aller-retour (Zanzibar-Arusha-Zanzibar)",
      "Transport en Toyota Land Cruiser 4x4 avec toit ouvrant",
      "1 nuit au lodge choisi (Karatu)",
      "Tous les repas (petit-déjeuner, déjeuner, dîner)",
      "Frais d'entrée aux parcs",
      "Guide francophone/anglophone",
    ],
    includedEn: [
      "Pickup and return at Arusha airport",
      "Round-trip domestic flight (Zanzibar-Arusha-Zanzibar)",
      "Transport in Toyota Land Cruiser 4x4 with open roof",
      "1 night at chosen lodge (Karatu)",
      "All meals (breakfast, lunch, dinner)",
      "Park entry fees",
      "French/English-speaking guide",
    ],
  },
  {
    id: "mikumi-3days",
    titleFr: "3 Jours 2 Nuits — Parc National de Mikumi",
    titleEn: "3 Days 2 Nights — Mikumi National Park",
    descriptionFr: "Le safari de 3 jours 2 nuits dans le parc national de Mikumi. Découverte des animaux sauvages et visite d'un village masaï avec coucher de soleil.",
    descriptionEn: "3 days 2 nights safari in Mikumi National Park. Discover wildlife and visit a Maasai village at sunset.",
    duration: "3 Jours / 2 Nuits",
    price: "350€ - 450€ par personne",
    coverImage: "/images/ jours 2 nuits dans le parc national de mikumi. 11.jpeg",
    images: [
      "/images/ jours 2 nuits dans le parc national de mikumi. 11.jpeg",
      "/images/ jours 2 nuits dans le parc national de mikumi. .jpeg",
      "/images/ jours 2 nuits dans le parc national de mikumi. 2.jpeg",
      "/images/ jours 2 nuits dans le parc national de mikumi. 3.jpeg",
    ],
    itineraryFr: [
      {
        day: 1,
        title: "Zanzibar → Dar es Salaam → Morogoro → Mikumi",
        description: "Départ à 7h du matin en ferry de Zanzibar, arrivée à Dar es Salaam à 8h50. Train jusqu'à Morogoro (1h30), puis voiture jusqu'à Mikumi (2h). À l'hôtel, douche et repas. En soirée, visite d'un village masaï avec coucher de soleil. Retour à l'hôtel vers 19h30 pour le dîner.",
      },
      {
        day: 2,
        title: "Safari — Mikumi",
        description: "Safari en jeep toute la journée dans le parc national de Mikumi. Observation des animaux sauvages : lions, éléphants, buffles, zèbres, girafes... Repas dans le parc. Une journée inoubliable au cœur de la savane tanzanienne.",
      },
      {
        day: 3,
        title: "Mikumi → Zanzibar",
        description: "Petit-déjeuner matinal, puis retour vers Dar es Salaam. Repas en chemin. Ferry pour Zanzibar. Fin du safari.",
      },
    ],
    itineraryEn: [
      {
        day: 1,
        title: "Zanzibar → Dar es Salaam → Morogoro → Mikumi",
        description: "Depart at 7am by ferry from Zanzibar, arrive Dar es Salaam at 8:50am. Train to Morogoro (1.5h), then drive to Mikumi (2h). At the hotel, shower and meal. In the evening, visit a Maasai village at sunset. Return to hotel around 7:30pm for dinner.",
      },
      {
        day: 2,
        title: "Safari — Mikumi",
        description: "Full-day jeep safari in Mikumi National Park. Wildlife spotting: lions, elephants, buffalo, zebras, giraffes... Meals in the park. An unforgettable day in the heart of the Tanzanian savanna.",
      },
      {
        day: 3,
        title: "Mikumi → Zanzibar",
        description: "Early breakfast, then return toward Dar es Salaam. Lunch on the way. Ferry back to Zanzibar. End of safari.",
      },
    ],
    includedFr: [
      "Transfert aller-retour",
      "Ferry Zanzibar ↔ Dar es Salaam",
      "Train et voiture jusqu'à Mikumi",
      "Jeep 4x4 pour le safari",
      "Guide local",
      "2 nuits à l'hôtel",
      "Tous les repas",
      "Visite village masaï",
      "Frais d'entrée du parc",
    ],
    includedEn: [
      "Round-trip transfer",
      "Ferry Zanzibar ↔ Dar es Salaam",
      "Train and car to Mikumi",
      "4x4 jeep for safari",
      "Local guide",
      "2 hotel nights",
      "All meals",
      "Maasai village visit",
      "Park entry fees",
    ],
  },
  {
    id: "serengeti-ngorongoro",
    titleFr: "Serengeti + Ngorongoro — 3 Jours / 2 Nuits",
    titleEn: "Serengeti + Ngorongoro — 3 Days / 2 Nights",
    descriptionFr: "Grande migration, cratère Ngorongoro, game drives privés et nuit en camp dans la savane.",
    descriptionEn: "Great migration, Ngorongoro Crater, private game drives and a night in a savanna camp.",
    duration: "3 Jours / 2 Nuits",
    price: "Sur demande",
    coverImage: "/images/serengeti-1.jpeg",
    images: [
      "/images/serengeti-1.jpeg",
      "/images/serengeti-2.jpeg",
      "/images/serengeti-3.jpeg",
      "/images/serengeti-4.jpeg",
      "/images/serengeti-6.jpeg",
      "/images/safari-maasai.jpeg",
    ],
    itineraryFr: [
      {
        day: 1,
        title: "Zanzibar → Serengeti",
        description: "Départ de Zanzibar vers l'aéroport de Seronera en Tanzanie. Votre jeep privée vous attend pour commencer le safari vers 11h00. Game drive jusqu'à 13h00, pique-nique dans la savane, puis visite jusqu'à 18h00. Dîner et nuit au Serengeti Sound Camp.",
      },
      {
        day: 2,
        title: "Serengeti → Karatu",
        description: "Réveil à 6h00, petit-déjeuner matinal. Game drive toute la matinée jusqu'à midi. Déjeuner et repos. Départ pour Karatu, arrivée vers 16h00. Repos à l'hôtel 'Farm of Dream'. Possibilité de nager en piscine et se balader en ville.",
      },
      {
        day: 3,
        title: "Ngorongoro → Zanzibar",
        description: "Dernière journée — visite du cratère Ngorongoro, l'un des plus beaux spectacles naturels d'Afrique. Game drive toute la journée. Pique-nique dans le parc vers 13h00. Départ pour Arusha puis retour à Zanzibar.",
      },
    ],
    itineraryEn: [
      {
        day: 1,
        title: "Zanzibar → Serengeti",
        description: "Depart Zanzibar to Seronera Airport in Tanzania. Your private jeep awaits to begin the safari around 11:00am. Game drive until 1:00pm, picnic in the savanna, then continue until 6:00pm. Dinner and overnight at Serengeti Sound Camp.",
      },
      {
        day: 2,
        title: "Serengeti → Karatu",
        description: "Wake up at 6:00am, early breakfast. Morning game drive until midday. Lunch and rest. Depart for Karatu, arriving around 4:00pm. Rest at the 'Farm of Dream' hotel. Option to swim in the pool and explore the town.",
      },
      {
        day: 3,
        title: "Ngorongoro → Zanzibar",
        description: "Last day — visit to Ngorongoro Crater, one of Africa's most spectacular natural sights. Full-day game drive. Picnic in the park around 1:00pm. Depart for Arusha then return to Zanzibar.",
      },
    ],
    includedFr: [
      "Transport en jeep 4x4 privée",
      "Guide anglophone/francophone",
      "Nuit en camp (Serengeti Sound Camp)",
      "Nuit à l'hôtel Farm of Dream (Karatu)",
      "Tous les repas (pique-nique + dîner)",
      "Frais d'entrée des parcs",
      "Vol Zanzibar ↔ Serengeti",
    ],
    includedEn: [
      "Private 4x4 jeep transport",
      "English/French-speaking guide",
      "1 night at Serengeti Sound Camp",
      "1 night at Farm of Dream hotel (Karatu)",
      "All meals (picnic + dinner)",
      "Park entry fees",
      "Flight Zanzibar ↔ Serengeti",
    ],
  },
];
